### PR TITLE
Throw if connect() is called before claiming access

### LINKED ISSUE #1198: Check if access is claimed when connecting
I just added the library to a test app and forgot to claim a scope. It will just fail with an error message, but not a helpful one for new developers.

### PR DESCRIPTION
**Pull request by ssisk**
Fixes #1198

Hello! I ran into this issue and I thought I'd go ahead and submit a fix since it seems like a nice small change.

### CODE REVIEW

**Review by DougReeder — APPROVED** [review]

File: test/unit/authorize-suite.js [hunk 1]
```diff
@@ -108,6 +108,27 @@ define([ 'require', './build/authorize', './build/unauthorized-error'], function
...
+          this.localStorageAvailable = function() { return true; };
+
+          var sawError = false;
+          try {
+          env.Authorize.authorize(this, {authURL, scope, redirectUri, clientId});
+          } catch (e) {
+            test.assert(e.message.includes("scope"), true, "Did not throw an error that had a message describing the problem");
+            sawError = true;
+          }
+          test.assert(sawError, true, "Did not throw an error when scope was not set");
```
Comment (raucao) [inline test/unit/authorize-suite.js:128]: The descriptions of the assertions should be human-readable language of what is being asserted. When the test fails, it will then show that e.g. "throws an error when scope is not set" was expected, but did not satisfy the expectation.

**Review by raucao — CHANGES_REQUESTED** [review]
Welcome @ssisk! And thanks for your first contribution! :tada: 

I just have a minor nitpick about wording, but overall it's looking good to me.

File: test/unit/authorize-suite.js (hunk 1 above)
Comment (ssisk) [reply test/unit/authorize-suite.js]: Thanks for the feedback! I've updated the assertions' text so that they should match the convention, let me know if not.

**Review by raucao — APPROVED** [review]
:+1:

File: test/unit/authorize-suite.js (hunk 1 above)
Comment (raucao) [reply test/unit/authorize-suite.js]: Great, thanks!
