### PR TITLE
Fix authorize hash cleanup for non-OAuth fragments

### LINKED ISSUE #1373: `location.hash` is cleared on every construction, not just OAuth callbacks
## Problem

`new RemoteStorage(...)` unconditionally wipes `window.location.hash` on every page load — not just after OAuth callbacks. This breaks hash-based SPA routers (`#/route`) that use the fragment for navigation: any route hash (e.g. `#/todos`, `#/collections`) is stripped synchronously during construction, and the resulting `hashchange` sends the router to its default route.

## Reproduce

```js
// URL: https://example.com/#/todos
import RemoteStorage from 'remotestoragejs';
const rs = new RemoteStorage({});
// URL after construction: https://example.com/#
// (hashchange fires: #/todos → #)
```

## Root cause

[`src/authorize.ts` lines 271-278](https://github.com/remotestorage/remotestorage.js/blob/master/src/authorize.ts#L271-L278):

```ts
static _rs_init = function (remoteStorage: RemoteStorage): void {
  const params = extractParams();
  let location: Location;

  if (params) {
    location = Authorize.getLocation();
    location.hash = '';
  }
  ...
```

The `if (params)` guard is intended to mean "only clear when this is an OAuth callback", but `extractParams()` always returns at least `{}` (empty object), and `{}` is truthy in JavaScript. So the guard never fails and the hash is always cleared.

## Scenarios

| URL hash | Query string | `extractParams()` returns | `if (params)` | Hash cleared? |
|---|---|---|---|---|
| `#/todos` | none | `{}` | truthy | ✓ (bug) |
| `#foo=bar` | none | `{foo: 'bar'}` | truthy | ✓ (arguably bug — see #1180) |
| (empty) | `?q=1` | `{q: '1'}` | truthy | ✓ (no-op) |
| (empty) | none | `{}` | truthy | ✓ (no-op) |

## Suggested fix

Gate the cleanup on an actual OAuth-callback shape rather than a truthy-object check:

```ts
const isOAuthCallback = !!(
  params.access_token ||
  params.code ||
  params.error ||
  params.remotestorage ||
  params.rsDiscovery ||
  params.state
);

if (isOAuthCallback) {
  location = Authorize.getLocation();
  location.hash = '';
}
```

This aligns with the intent of #1180 and also handles the present case, where the hash has no `=` at all but still gets wiped.

## Related

- #1180 — "Hash is removed if it contains an `=`." describes the same over-aggressive cleanup, but its title/description only covers the `=`-containing case. The actual condition is broader: the hash is cleared for **any** fragment, regardless of whether it looks OAuth-shaped.

## Workaround

Consumers can snapshot `window.location.hash` before `new RemoteStorage()` and restore it with `history.replaceState` afterwards (replaceState avoids firing a spurious `hashchange`).

## Version

`2.0.0-beta.8` — also present on `master` as of this writing.

## Impact

Any SPA that uses hash-based routing (`#/foo`) alongside remotestorage.js loses its route on every page load/refresh. The bug is especially confusing because it fires synchronously inside the constructor — the symptom looks like the app's own router is misbehaving, not the RS library.

### PR DESCRIPTION
**Pull request by silverbucket**
## Summary
- limit authorize hash cleanup to actual remoteStorage OAuth callback parameters
- preserve SPA and other application hashes that are unrelated to OAuth
- add Mocha and legacy Jaribu regression coverage for both callback and non-callback fragments

## Root cause
`Authorize._rs_init` cleared `location.hash` whenever `extractParams()` returned a truthy value. Since `extractParams()` always returns an object, non-OAuth fragments like `#/todos` and `#foo=bar` were being wiped during construction.

## Impact
Applications using hash-based routing no longer lose their current route when `RemoteStorage` is constructed, while real OAuth callback fragments are still cleaned up as before.

Closes https://github.com/remotestorage/remotestorage.js/issues/1373 and https://github.com/remotestorage/remotestorage.js/issues/1180

### CODE REVIEW

File: src/authorize.ts [hunk 1]
```diff
@@ -47,6 +47,15 @@ export interface AuthorizeOptions {
 // This is set in _rs_init and needed for removal in _rs_cleanup
 let onFeaturesLoaded: EventHandler;
 
+function hasAuthCallbackParams (params: AuthResult): boolean {
+  return typeof params.access_token === 'string' ||
+    typeof params.code === 'string' ||
+    typeof params.error === 'string' ||
+    typeof params.remotestorage === 'string' ||
+    typeof params.state === 'string' ||
```
Comment (raucao) [inline src/authorize.ts]: This would still clear params if only the `state` param is set, which is probably not what we want.

**Review by raucao — CHANGES_REQUESTED** [review]
Funny, I just ran into the same issue, but it was only cosmetic in my case, so I didn't fix it immediately. Definitely an important bugfix!

**Review by raucao — APPROVED** [review]
