### PR TITLE
Fix binary detection for Dropbox and Google Drive

### LINKED ISSUE #1059: Problem detecting binary files in Dropbox and Google Drive
As noticed in #1049, when GETting a file from Dropbox, the content-type is always `application/octet-stream` without a charset. So our way of detecting binary data (see https://github.com/remotestorage/remotestorage.js/blob/4cfea9b466554b3195d4233253175259bca872fb/src/dropbox.js#L430) doesn't work.

### PR DESCRIPTION
**Pull request by galfert**
Fixes #1059

With this fix, downloaded binary data is returned as ArrayBuffer, similar to binaries from a remoteStorage backend.

### CODE REVIEW

**Comment by galfert** [comment]
I haven't looked into how to write a test for this yet. But you can already have a look and maybe give it a try.

I made some changes to Sharesome to test the fix. I'll push that branch somewhere so you can use it as well.

**Comment by skddc** [comment]
Ok, great.

File: src/util.js [hunk 1]
```diff
@@ -410,6 +410,52 @@
...
+     * Decide if data should be treated as binary based on the content
+     * and content-type.
+     *
+     * @param {string} content - The data
+     * @param {string} mimeType - The data's content-type
+     *
+     * @returns {boolean}
+     */
+    shouldBeTreatedAsBinary (content, mimeType) {
+      return !mimeType || mimeType.match(/charset=binary/) || /[\x00-\x1F]/.test(content);
```
Comment (skddc) [inline src/util.js]: I don't understand the first condition here. Why is it considered binary when the mimeType is unknown? Wouldn't it be more likely that it's text with RS documents, but have to be looked into especially in that case?

Comment (galfert) [reply src/util.js]: Yes, I'm not sure about this either. To be honest, I just used that because it already was like that before. I just added the last condition.

Comment (galfert) [reply src/util.js]: Especially with that new condition, the first condition should probably be removed.

Comment (skddc) [reply src/util.js]: Yup.

**Comment by galfert** [comment]
I pushed my test version of Sharesome to https://github.com/galfert/sharesome/tree/test_binary_download

On the history page, there is a "Download item" link for every shared item (not right at the item, just somewhere on the page, because no extra styling). Clicking that should log the downloaded file to the console.

Right now the branch is using remotestorage 1.0.0-rc3. So when using Dropbox or Google Drive, the logged file's data will just be a string. When using it with this PR's fix, it should be an `ArrayBuffer` instead, similar to the remoteStorage backend.

Btw, I noticed that in this Sharesome version, when the widget is minimized, the icon is cut off at the right side. I haven't looked into this yet. Maybe it's just the styling of the container the widget is added to. But we should check out that it's not another widget style that can be overwritten.

**Comment by gregkare** [comment]
@galfert I'm getting the following exception when clicking the "Download item" link:

```
Error while processing route: show Cannot read property 'getFile' of undefined TypeError: Cannot read property 'getFile' of undefined
    at Class.model (http://localhost:4200/assets/sharesome.js:759:42)
    at Class.deserialize (http://localhost:4200/assets/vendor.js:43186:19)
    at applyHook (http://localhost:4200/assets/vendor.js:61185:30)
    at C.runSharedModelHook (http://localhost:4200/assets/vendor.js:61781:20)
    at C.getModel (http://localhost:4200/assets/vendor.js:61979:19)
    at http://localhost:4200/assets/vendor.js:61038:17
    at tryCatch (http://localhost:4200/assets/vendor.js:63578:14)
    at invokeCallback (http://localhost:4200/assets/vendor.js:63591:15)
    at publish (http://localhost:4200/assets/vendor.js:63561:9)
    at http://localhost:4200/assets/vendor.js:54459:16
logError @ router.js:936
error @ router.js:879
triggerEvent @ router.js:1036
trigger @ router.js:111
trigger @ router.js:645
(anonymous) @ router.js:456
tryCatch @ rsvp.js:411
invokeCallback @ rsvp.js:424
publish @ rsvp.js:394
publishRejection @ rsvp.js:329
(anonymous) @ rsvp.js:14
invoke @ backburner.js:274
flush @ backburner.js:153
flush @ backburner.js:345
end @ backburner.js:455
run @ backburner.js:539
join @ backburner.js:546
run.join @ ember-metal.js:4309
(anonymous) @ has_element.js:18
exports.flaggedInstrument @ ember-metal.js:3730
handleEvent @ has_element.js:17
exports.default._emberMetal.Mixin.create._Mixin$create.handleEvent @ view_support.js:177
_bubbleEvent @ event_dispatcher.js:278
(anonymous) @ event_dispatcher.js:212
dispatch @ jquery.js:5206
elemData.handle @ jquery.js:5014
ember-metal.js:3927 TypeError: Cannot read property 'getFile' of undefined
    at Class.model (show.js:22)
    at Class.deserialize (route.js:946)
    at applyHook (router.js:244)
    at C.runSharedModelHook (router.js:840)
    at C.getModel (router.js:1038)
    at router.js:97
    at tryCatch (rsvp.js:411)
    at invokeCallback (rsvp.js:424)
    at publish (rsvp.js:394)
    at rsvp.js:14
```

Using this PR as the remotestoragejs npm package I'm getting things like "undefined/public/shares/171101-1851-5apps-logo-plain-black-large.png" as a URL when uploading files. The actual uploads work

**Comment by gregkare** [comment]
Oh, this is with Google Drive by the way

**Comment by gregkare** [comment]
On Dropbox uploading fails (I had to switch to my own API credentials):

```
POST https://content.dropboxapi.com/2/files/upload 400 (Bad Request)
upload.js:96 Request (PUT /public/shares/171101-1910-5apps-logo-plain-black-large.png) failed with status: 400
(anonymous) @ upload.js:96
Promise rejected (async)
submitFileUpload @ upload.js:87
send @ action_handler.js:32
(anonymous) @ action.js:141
exports.flaggedInstrument @ ember-metal.js:3730
(anonymous) @ action.js:140
run @ backburner.js:537
run @ ember-metal.js:4267
handler @ action.js:120
(anonymous) @ event_dispatcher.js:233
dispatch @ jquery.js:5206
elemData.handle @ jquery.js:5014
content.dropboxapi.com/2/files/upload:1 POST https://content.dropboxapi.com/2/files/upload 400 (Bad Request)
:4200/#:1 Uncaught (in promise) Request (PUT /public/shares/thumbnails/171101-1910-5apps-logo-plain-black-large.png.png) failed with status: 400
Promise rejected (async)
(anonymous) @ remotestorage.js:2
Promise resolved (async)
storeFile @ remotestorage.js:2
_storeThumbnail @ build.js:286
storeFile @ build.js:94
submitFileUpload @ upload.js:87
send @ action_handler.js:32
(anonymous) @ action.js:141
exports.flaggedInstrument @ ember-metal.js:3730
(anonymous) @ action.js:140
run @ backburner.js:537
run @ ember-metal.js:4267
handler @ action.js:120
(anonymous) @ event_dispatcher.js:233
dispatch @ jquery.js:5206
elemData.handle @ jquery.js:5014
api.dropboxapi.com/2/sharing/create_shared_link_with_settings:1 POST https://api.dropboxapi.com/2/sharing/create_shared_link_with_settings 409 (Conflict)
remotestorage.js:3 Uncaught (in promise) Error: Sharing Dropbox file or folder ("/public/shares/171101-1910-5apps-logo-plain-black-large.png") failed: API error: path/not_found/.
    at remotestorage.js:3
    at <anonymous>
(anonymous) @ remotestorage.js:3
Promise rejected (async)
(anonymous) @ remotestorage.js:3
Promise rejected (async)
share @ remotestorage.js:3
_shareIfNeeded @ remotestorage.js:3
(anonymous) @ remotestorage.js:3
Promise resolved (async)
put @ remotestorage.js:3
(anonymous) @ remotestorage.js:4
storeFile @ remotestorage.js:2
storeFile @ build.js:97
submitFileUpload @ upload.js:87
send @ action_handler.js:32
(anonymous) @ action.js:141
exports.flaggedInstrument @ ember-metal.js:3730
(anonymous) @ action.js:140
run @ backburner.js:537
run @ ember-metal.js:4267
handler @ action.js:120
(anonymous) @ event_dispatcher.js:233
dispatch @ jquery.js:5206
elemData.handle @ jquery.js:5014
api.dropboxapi.com/2/sharing/create_shared_link_with_settings:1 POST https://api.dropboxapi.com/2/sharing/create_shared_link_with_settings 409 (Conflict)
remotestorage.js:3 Uncaught (in promise) Error: Sharing Dropbox file or folder ("/public/shares/thumbnails/171101-1910-5apps-logo-plain-black-large.png.png") failed: API error: path/not_found/
    at remotestorage.js:3
```

**Comment by galfert** [comment]
> Using this PR as the remotestoragejs npm package I'm getting things like "undefined/public/shares/171101-1851-5apps-logo-plain-black-large.png" as a URL when uploading files. The actual uploads work

That's because the `getItemURL` for getting public links isn't implemented for Dropbox and GDrive yet. It's an open issue and is documented in the "known issues" as well.

**Comment by galfert** [comment]
> @galfert I'm getting the following exception when clicking the "Download item" link:
> 
>> Error while processing route: show Cannot read property 'getFile' of undefined TypeError: Cannot read property 'getFile' of undefined

Oh damn, right. I monkey-patched the shares module to export the publicClient.

You can do the same by editing `node_modules/remotestorage-module-shares/dist/build.js` and adding

```js
      client: publicClient,
```

inside of the `var shares = { ... }` block.

**Comment by galfert** [comment]
After reviewing @skddc's getting started guide, I realized that I could just have used `scope()` instead of monkey-patching the shares module :)

So I updated my Sharesome branch. No need to monkey patch anymore.

**Comment by skddc** [comment]
Haha, docs FTW! They're great for everyone, not just novice users. :)

**Comment by skddc** [comment]
Works!
