### PR TITLE
Don't fail when sync instance is not defined

### LINKED ISSUE #1117: Cannot read property 'stopped' of undefined
I'm getting this error in an integration test for an app that uses remoteStorage.js.

In that test, the app connects to remoteStorage and then pretty much immediately disconnects again. The error doesn't occur on every test run, but happens more often than not.

### PR DESCRIPTION
**Pull request by galfert**
Fixes #1117

### CODE REVIEW

File: src/remotestorage.js [hunk 1]
```diff
@@ -701,13 +701,13 @@ RemoteStorage.prototype = {
    * @private
    */
   syncCycle: function () {
-    if (this.sync.stopped) {
+    if (!this.sync || this.sync.stopped) {
```
Comment (skddc) [inline src/remotestorage.js]: Why not just use the same as below, which I think is a bit more standard?
